--!strict

local types = require(game.ReplicatedStorage.Functions.Types)

local templateSpecialsData = {}

templateSpecialsData.special1 = {
	name = '',
	keybind = '',
	cooldown = 0
} :: types.special

templateSpecialsData.special2 = {
	name = '',
	keybind = '',
	cooldown = 0
} :: types.special

templateSpecialsData.special3 = {
	name = '',
	keybind = '',
	cooldown = 0
} :: types.special

templateSpecialsData.special4 = {
	name = '',
	keybind = '',
	cooldown = 0
} :: types.special

templateSpecialsData.awakenedSpecial1 = {
	name = '',
	keybind = '',
	cooldown = 0
} :: types.special

templateSpecialsData.awakenedSpecial2 = {
	name = '',
	keybind = '',
	cooldown = 0
} :: types.special

templateSpecialsData.awakenedSpecial3 = {
	name = '',
	keybind = '',
	cooldown = 0
} :: types.special

templateSpecialsData.awakenedSpecial4 = {
	name = '',
	keybind = '',
	cooldown = 0
} :: types.special

return templateSpecialsData
